FROM python:3-alpine

LABEL maintainer="core-tech@better.com"

RUN apk add make git openssh docker
RUN pip install boto3 crontab PyYaml pytest pytest-cov pytest-html requests

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev \
 && pip install moto \
 && apk del .build-deps
