FROM node:alpine

LABEL maintainer="core-tech@better.com"

RUN apk add make git openssh
RUN npm -g install lodash js-yaml fs-extra mocha chai sinon nock aws-sdk-mock

ENV NODE_PATH /usr/local/lib/node_modules
