#!/bin/bash
export BASE_APK_DEPENDENCIES=(
  bash
  curl
  openssl
  coreutils
  ca-certificates
  # qpid proton (for activemq) needs this library to authenticate
  cyrus-sasl-plain
  # librdkafka needs these .so's at runtime
  lz4-dev
  cyrus-sasl-dev
)

export BUILD_APK_DEPENDENCIES=(
  jq
  git
  tar
  make
  gnupg
  docker
  openssh
  yaml-dev
  zlib-dev
  build-base
  libffi-dev
  libxslt-dev
  openssl-dev
  linux-headers
  libjpeg-turbo-dev
)

# Will this work on Docker Hub? Is `git` available? Should be...
git_root=$(git rev-parse --show-toplevel)

# ${IMAGE_NAME}      is defined by Docker Hub: {repo}:{tag}
# ${DOCKERFILE_PATH} is defined by Docker Hub: {path}
docker build                                                        \
  --build-arg BASE_APK_DEPENDENCIES="${BASE_APK_DEPENDENCIES[*]}"   \
  --build-arg BUILD_APK_DEPENDENCIES="${BUILD_APK_DEPENDENCIES[*]}" \
  --tag  "${IMAGE_NAME}"                                            \
  --file "${git_root}/${DOCKERFILE_PATH}"                           \
  ${git_root}
