FROM better/dockerimages:build-python-latest AS builder

FROM python:3-alpine

LABEL maintainer="core-tech@better.com"

# Install the base requirements
COPY scripts/common.sh common.sh
RUN apk update && apk upgrade && chmod +x common.sh && ./common.sh

# Librdkafka for event service dependents
COPY --from=builder /usr/lib/librdkafka.so /usr/lib/librdkafka.so
